Repository korinreloj/medium-wp, pull requests merged in 2018-08, with the labels that each got.

#48 🍱 FE: Featured Content
  wp-content/themes/medium-wp/assets/scss/components/_feature-content.scss
  wp-content/themes/medium-wp/assets/scss/styles.css
  wp-content/themes/medium-wp/assets/scss/styles.css.map
  wp-content/themes/medium-wp/featured-content.php
Labels: FE

#49 🍱 BE: Updated main-feed.php
  wp-content/themes/medium-wp/ACF/article-fields.php
  wp-content/themes/medium-wp/ACF/flexible-content.php
  wp-content/themes/medium-wp/ACF/main_feed.php
  wp-content/themes/medium-wp/functions.php
  wp-content/themes/medium-wp/main-feed.php
  wp-content/themes/medium-wp/page.php
  wp-content/themes/medium-wp/single.php
Labels: BE

#50 🍱 Integrated BE and FE for Main Feed
  wp-content/themes/medium-wp/assets/scss/components/_feed-sidebar.scss
  wp-content/themes/medium-wp/assets/scss/components/_main-feed.scss
  wp-content/themes/medium-wp/assets/scss/components/main-feed.css
  wp-content/themes/medium-wp/assets/scss/components/main-feed.css.map
  wp-content/themes/medium-wp/main-feed.php
Labels: BE, FE
